services:
  - type: web
    name: datamedic-ai
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FRONTEND_URL
        sync: false